### ISSUE TITLE
Planned functions

### ISSUE THREAD

**Issue by FabianBartl** [FabianBartl/HARIBOT#20]
## Planned functions

- [ ] `/help` [#8](https://github.com/FabianBartl/HARIBOT/issues/8) [#9](https://github.com/FabianBartl/HARIBOT/issues/9)

<br>

- [x] `/ping`

<br>

- [x] `/log [action]` *(only for admins)* [#11](https://github.com/FabianBartl/HARIBOT/issues/11)
  - actions:
    - [x] backup, save, get, list
    - [x] clear, reset *(only for owner)*

<br>

- [ ] `/member-info [member]` [#18](https://github.com/FabianBartl/HARIBOT/issues/18)
- [x] `/server-info`
- [ ] `/bot-info` [#19](https://github.com/FabianBartl/HARIBOT/issues/19)

<br>

- [ ] `/auto-role [action] [type] [role]` [#12](https://github.com/FabianBartl/HARIBOT/issues/12)
  - actions:
    - [ ] add, list, remove, clear

<br>

- [ ] `/reaction-role [action] [messageID] [emoji] [role]` [#10](https://github.com/FabianBartl/HARIBOT/issues/10)
  - actions:
    - [ ] add, list, remove, clear

<br>

- [ ] `/pgp-get [member]` [#18](https://github.com/FabianBartl/HARIBOT/issues/18)
- [ ] `/pgp-set [key] [email]`
- [ ] `/pgp-delete [email]`

<br>

- [ ] `/what-if` [#17](https://github.com/FabianBartl/HARIBOT/issues/17)
